In [1]:
print("Hello Natural Language Processing!")

Hello Natural Language Processing!


# 第１章: ニューラルネットワークの復習

## 1.1: 数学とPythonの復習


### 1.1.1: ベクトルと行列

ベクトルとは大きさと向きを持つ量であり，数が一列にならんだ集まりとして表現できる．<br>
行列とは二次元状に並んだ数の集まりでり，数が長方形上にならんだ集まりとして表現できる．


In [10]:
import numpy as np

x = np.array([1, 2, 3])
print(f"x = {x}")
print(f"x_class = {x.__class__}")
print(f"x_shape = {x.shape}")
print(f"x_ndim = {x.ndim}")

W = np.array([[1, 2, 3], [4, 5, 6]])
print(f"W = {W}")
print(f"W_shape = {W.shape}")

x = [1 2 3]
x_class = <class 'numpy.ndarray'>
x_shape = (3,)
x_ndim = 1
W = [[1 2 3]
 [4 5 6]]
W_shape = (2, 3)


x.shapeは多次元配列の形状を，x.ndimは次元数を表す．<br>
例として<br>

- {x} は1次元の配列であり，要素数が3のベクトルである．<br>
- {W} は2次元の配列であり，2×3（2行3列）の行列である．


### 1.1.2: 行列の要素ごとの演算


In [11]:
W = np.array([[1, 2, 3], [4, 5, 6]])
X = np.array([[0, 1, 2], [3, 4, 5]])

print(f"W + X = {W + X}")
print(f"W * X = {W * X}")

W + X = [[ 1  3  5]
 [ 7  9 11]]
W * X = [[ 0  2  6]
 [12 20 30]]


### 1.1.3: ブロードキャスト

numpyの多次元配列では形状の異なる配列どうしでの演算も可能であり，以下のように表せる．


In [14]:
A = np.array([[1, 2], [3, 4]])
print(f"A+10 = {A + 10}")
print(f"A*10 = {A * 10}")

A+10 = [[11 12]
 [13 14]]
A*10 = [[10 20]
 [30 40]]
