# Chapter１


## 1.1 Numpy


In [ ]:
import numpy as np


def inspect_tensor(name, x):
    """
    テンソル(配列)の情報を構造的に表示するデバッグ用関数
    The Code Smith Recommended
    """
    print(f"\n--- [Inspect: {name}] ---")
    print(f"Shape (形状) : {x.shape}")
    print(f"Rank  (次元数): {x.ndim}")
    print(f"Dtype (データ型): {x.dtype}")
    print(f"Data:\n{x}")
    print("-" * 30)


# ==========================================
# 1. データの定義 (Data Definition)
# ==========================================
# Deep Learningでは、これを「テンソル」と呼ぶ。
# 今回は 2x2 の行列 (Matrix) である。

A = np.array([[1, 2], [3, 4]])

B = np.array([[5, 6], [7, 8]])

inspect_tensor("A", A)
inspect_tensor("B", B)

# ==========================================
# 2. 要素ごとの演算 (Element-wise Operations)
# ==========================================
# 注意: Deep Learningの数式で単に "+" や "⊙" (Hadamard product) と書かれるもの。
# ルール: AとBの shape が完全に一致している必要がある。
# (または後述のブロードキャストが可能であること)

print("\n=== 1. Element-wise Operations (要素ごと) ===")

# 足し算: 同じ位置の要素同士を足す
# [[1+5, 2+6],
#  [3+7, 4+8]]
add_result = A + B
print(f"A + B (Addition):\n{add_result}")

# ★重要★ 掛け算 ( ' * ' 演算子)
# 数学的な「行列の掛け算」ではない！
# 単なる「同じ場所にある数字同士の掛け算」である。
# [[1*5, 2*6],
#  [3*7, 4*8]]
element_wise_mult = A * B
print(f"A * B (Element-wise Multiplication):\n{element_wise_mult}")


# ==========================================
# 3. 行列積 (Dot Product / Matrix Multiplication)
# ==========================================
# ★最重要★ Deep Learningの「層（レイヤ）」の計算はこれだ。
# 数式: Y = X・W
# ルール: 左側の行列の「列数」と、右側の行列の「行数」が一致しなければならない。
# (N, M) dot (M, K) -> (N, K)

print("\n=== 2. Dot Product (行列積) ===")

# Python 3.5以上では '@' 演算子が推奨される (np.dot(A, B)と同じ)
# 計算手順の可視化:
# [[1*5 + 2*7,  1*6 + 2*8],
#  [3*5 + 4*7,  3*6 + 4*8]]
#
# [[5+14,  6+16],
#  [15+28, 18+32]]

dot_result = A @ B  # または A.dot(B)
print(f"A @ B (Dot Product):\n{dot_result}")


# ==========================================
# 4. ブロードキャスト (Broadcasting)
# ==========================================
# NumPyの真骨頂。形状が合わない場合、自動で拡張して計算する。
# バイアス項の加算などで多用する。

print("\n=== 3. Broadcasting (ブロードキャスト) ===")

C = np.array([10, 20])  # Shape: (2,)
inspect_tensor("C (Scalar-like vector)", C)

# Aは (2, 2)、Cは (2,)
# NumPyはCを勝手に [[10, 20], [10, 20]] に拡張(コピー)して計算してくれる。
broadcast_result = A * C
print(f"A * C (Broadcasting):\n{broadcast_result}")
# 解説:
# [1, 2] * [10, 20] -> [10, 40]
# [3, 4] * [10, 20] -> [30, 80]


# ==========================================
# 5. よく使う便利機能 (Common Utils)
# ==========================================
print("\n=== 4. Useful Utils ===")

# 転置 (Transpose): 行と列を入れ替える
# 逆伝播(Backpropagation)の実装で死ぬほど使う。
print(f"A.T (Transpose):\n{A.T}")

# Flatten: 一列に並べる
# 画像データ(2次元)をニューラルネットワークの入力(1次元)にする時に使う。
print(f"A.flatten(): {A.flatten()}")


--- [Inspect: A] ---
Shape (形状) : (2, 2)
Rank  (次元数): 2
Dtype (データ型): int64
Data:
[[1 2]
 [3 4]]
------------------------------

--- [Inspect: B] ---
Shape (形状) : (2, 2)
Rank  (次元数): 2
Dtype (データ型): int64
Data:
[[5 6]
 [7 8]]
------------------------------

=== 1. Element-wise Operations (要素ごと) ===
A + B (Addition):
[[ 6  8]
 [10 12]]
A * B (Element-wise Multiplication):
[[ 5 12]
 [21 32]]

=== 2. Dot Product (行列積) ===
A @ B (Dot Product):
[[19 22]
 [43 50]]

=== 3. Broadcasting (ブロードキャスト) ===

--- [Inspect: C (Scalar-like vector)] ---
Shape (形状) : (2,)
Rank  (次元数): 1
Dtype (データ型): int64
Data:
[10 20]
------------------------------
A * C (Broadcasting):
[[10 40]
 [30 80]]

=== 4. Useful Utils ===
A.T (Transpose):
[[1 3]
 [2 4]]
A.flatten(): [1 2 3 4]


# Chapter２


# Chapter３


# Chapter４


# Chapter５


# Chapter６


# Chapter７


# Chapter８
