In [1]:
# 算術計算
print(1 - 2)
print(4 * 5)
print(7 / 5)
print(3**2)

-1
20
1.4
9


In [2]:
# データ型
print(type(10))
print(type(2.718))
print(type("Hello"))

<class 'int'>
<class 'float'>
<class 'str'>


In [3]:
# 変数
x = 10
print(x)

x = 100
print(x)

y = 3.14
print(y)
print(x * y)

10
100
3.14
314.0


In [4]:
# リスト
Demo_List = [1, 2, 3, 4, 5]
print(Demo_List)

len(Demo_List)

Demo_List[0]

Demo_List[4]
Demo_List[4] = 100
print(Demo_List)

print(Demo_List[0:2])
print(Demo_List[1:])
print(Demo_List[:3])
print(Demo_List[:-1])

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 100]
[1, 2]
[2, 3, 4, 100]
[1, 2, 3]
[1, 2, 3, 4]


In [5]:
# ディクショナリ
Demo_Dictionary = {"Height": 155}
print(Demo_Dictionary)

print(Demo_Dictionary["Height"])

Demo_Dictionary["Weight"] = 56
print(Demo_Dictionary)

{'Height': 155}
155
{'Height': 155, 'Weight': 56}


In [6]:
# ブーリアン
Hungry = True
Sleepy = False
type(Hungry)

print(not Hungry)

print(not Sleepy)

print(Hungry and Sleepy)
print(Hungry or Sleepy)

False
True
False
True


In [7]:
# if文
Hungry = False
if Hungry:
    print("I'm Hungrry")
else:
    print("I'm not hungry")
    print("I'm sleepy")

I'm not hungry
I'm sleepy


In [8]:
# for文
for i in [1, 2, 3]:
    print(i)

1
2
3


In [9]:
# 関数
def hello():
    print("Hello World")


hello()


def hello(object):
    print("Hello" + object + "!")


hello("Cat")

Hello World
HelloCat!


In [10]:
# クラス
class Man:
    def __init__(self, name):
        self.name = name
        print("Initialized!")

    def hello(self):
        print("Hello " + self.name + "!")

    def goodbye(self):
        print("goodbye " + self.name + "!")


m = Man("Mari")
m.hello()
m.goodbye()

Initialized!
Hello Mari!
goodbye Mari!


In [12]:
# Numpy
import numpy as np

x = np.array([1.0, 2.0, 3.0])
print(x)

type(x)

[1. 2. 3.]


numpy.ndarray

In [13]:
# Numpy配列の生成と算術計算
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

print(x - y)
print(x * y)
print(x / y)

[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [14]:
# NumpyのN次元配列
A = np.array([[1, 2], [3, 4]])
print(A)
print(A.shape)
print(A.dtype)

[[1 2]
 [3 4]]
(2, 2)
int64


In [15]:
# ブロードキャスト
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])
print(A * B)

C = np.array([[1, 2], [3, 4]])
D = np.array([[10, 20], [30, 40]])
print(C * D)

[[10 40]
 [30 80]]
[[ 10  40]
 [ 90 160]]


In [16]:
# 要素へのアクセス
x = np.array([[51, 55], [14, 19], [0, 4]])
print(x)

print(x[0])
print(x[0][1])

x = x.flatten()
print(x)

x[np.array([0, 2, 4])]

print(x > 15)
print(x[x > 5])

[[51 55]
 [14 19]
 [ 0  4]]
[51 55]
55
[51 55 14 19  0  4]
[ True  True False  True False False]
[51 55 14 19]


In [ ]:
# Matplotlib
# pip install matplotlib

: 

In [ ]:
# 単純なグラフの描画
import numpy as np
import matplotlib.pyplot as plt

# データの作成
x = np.arange(0, 10, 0.1)
y = np.sin(x)

plt.plot(x, y)
plt.show()

In [ ]:
# pyplotの機能
import numpy as np
import matplotlib.pyplot as plt

# データの作成
x = np.arange(0, 6, 0.1)

y1 = np.sin(x)
y2 = np.cos(x)
# y3 = np.tan(x)

plt.plot(x, y1, label="sin")
plt.plot(x, y2, linestyle="--", label="cos")
# plt.plot(x, y3, label = "tan")

In [ ]:
# 画像の表示
import matplotlib.pyplot as plt
from matplotlib.image import imread

img = imread("../materials/pythoned.png")
plt.imshow(img)

plt.show()