In [10]:
Apple_cost = 100
current_tax = 0.1
peacies = 2
total_cost = Apple_cost * (1 + current_tax) * peacies
print("total_cost:", total_cost)


class MulLayer:
    def __init__(self):
        self.x = None
        self.y = None

    # 順伝播（行き）：ただの掛け算
    def forward(self, x, y):
        self.x = x  # 逆伝播のために覚えておく！
        self.y = y  # 逆伝播のために覚えておく！
        out = x * y
        return out

    # 逆伝播（帰り）：ひっくり返して掛ける
    def backward(self, dout):
        # dout は「上流から流れてきた微分」（さっきの例だと 1.1）
        dx = dout * self.y  # xの勾配には y を掛ける
        dy = dout * self.x  # yの勾配には x を掛ける

        return dx, dy


# 1. レイヤを作る
mul_apple_layer = MulLayer()  # リンゴ * 個数
mul_tax_layer = MulLayer()  # (リンゴ*個数) * 消費税

# 2. 順伝播（買い物をする）
apple = 100
apple_num = 2
tax = 1.1

# 最初の計算: 100 * 2 = 200
apple_price = mul_apple_layer.forward(apple, apple_num)
# 次の計算: 200 * 1.1 = 220
price = mul_tax_layer.forward(apple_price, tax)

print(f"支払金額: {price}")

# 3. 逆伝播（犯人探し）
d_price = 1  # スタートの信号は常に 1
d_apple_price, d_tax = mul_tax_layer.backward(d_price)
d_apple, d_apple_num = mul_apple_layer.backward(d_apple_price)

print(f"リンゴの値段の勾配: {d_apple}")
print(f"リンゴの個数の勾配: {d_apple_num}")
print(f"消費税の勾配: {d_tax}")

total_cost: 220.00000000000003
支払金額: 220.00000000000003
リンゴの値段の勾配: 2.2
リンゴの個数の勾配: 110.00000000000001
消費税の勾配: 200


In [11]:
class AddLayer:
    def __init__(self):
        pass  # 何も覚える必要なし

    def forward(self, x, y):
        return x + y

    def backward(self, dout):
        dx = dout * 1
        dy = dout * 1
        return dx, dy


# レイヤの準備
mul_apple_layer = MulLayer()
mul_orange_layer = MulLayer()
add_apple_orange_layer = AddLayer()
mul_tax_layer = MulLayer()

# --- 1. 順伝播 (Forward) ---
apple = 100
apple_num = 2
orange = 150
orange_num = 3
tax = 1.1

# リンゴの値段
apple_price = mul_apple_layer.forward(apple, apple_num)  # 200
# ミカンの値段
orange_price = mul_orange_layer.forward(orange, orange_num)  # 450
# 合算
all_price = add_apple_orange_layer.forward(apple_price, orange_price)  # 650
# 消費税込み
price = mul_tax_layer.forward(all_price, tax)  # 715

print(f"支払総額: {price}")

# --- 2. 逆伝播 (Backward) ---
dprice = 1
dall_price, dtax = mul_tax_layer.backward(dprice)  # 1.1 と 650
dapple_price, dorange_price = add_apple_orange_layer.backward(
    dall_price
)  # そのまま流す
dorange, dorange_num = mul_orange_layer.backward(dorange_price)  # ？？？
dapple, dapple_num = mul_apple_layer.backward(dapple_price)

print(f"ミカンの値段の勾配(dorange): {dorange}")

支払総額: 715.0000000000001
ミカンの値段の勾配(dorange): 3.3000000000000003


In [12]:
# class SFC_Polymath_2026(UniversityStudent):
#     def __init__(self):
#         # 1. Computer Science (The Backbone)
#         self.cs_foundation = {
#             "Algorithms": "Master",
#             "Philosophy": "Absorb",
#             "Architecture": "Build",
#         }
#         # 2. Mathematics (The Engine)
#         self.math_engine = {
#             "Matrix": "Visualize",
#             "Calculus": "Derive",
#             "Prob_Stats": "Intuition",
#         }

#         # 3. Artificial Intelligence (The Brain)
#         self.ai_core = [
#             "Deep Learning (Scratch)",
#             "Machine Learning (Scikit-Learn)",
#             "Reinforcement Learning",
#         ]

#         # 4. Large Language Models (The Soul)
#         self.llm_capability = {
#             "Architecture": "Transformer",
#             "Application": "RAG & Agents",
#             "Creation": "Fine-tuning",
#         }

#         # 5. World Creation (The Stage)
#         self.simulation = "Unity ML-Agents (Simulate the World)"

#     def run_year_2025(self):

#         while True:
#             try:
#                 knowledge = self.read_all_books(library_path="./My_Weaponry")
#                 self.connect_dots(math=self.math_engine, code=self.cs_foundation)
#                 project = self.create_polaris(
#                     ai=self.ai_core, llm=self.llm_capability, sim=self.simulation
#                 )
#                 print(f"World Changed: {project}")
#             except BurnOutError:
#                 self.sleep(8)
#                 self.restart()

In [13]:
class MulLayer:
    def __init__(self):
        self.x = None
        self.y = None

    def forward(self, x, y):
        self.x = x
        self.y = y
        out = x * y

        return out

    def backward(self, dout):
        dx = dout * self.y
        dy = dout * self.x

        return dx, dy


apple = 100
apple_num = 2
tax = 1.1

mul_apple_layer = MulLayer()
mul_tax_layer = MulLayer()

apple_price = mul_apple_layer.forward(apple, apple_num)
price = mul_tax_layer.forward(apple_price, tax)

print(price)

dprice = 1
dapple_price, dtax = mul_tax_layer.backward(dprice)
dapple, dapple_num = mul_apple_layer.backward(dapple_price)


class AddLayer:
    def __init__(self):
        pass

    def forward(self, x, y):
        out = x + y
        return out

    def backward(self, dout):
        dx = dout * 1
        dy = dout * 1
        return dx, dy

220.00000000000003


In [14]:
apple = 100
apple_num = 2
orange = 150
orange_num = 3
tax = 1.1

mul_apple_layer = MulLayer()
mul_orange_layer = MulLayer()
add_apple_orange_layer = AddLayer()
mul_tax_layer = MulLayer()

apple_price = mul_apple_layer.forward(apple, apple_num)
orange_price = mul_orange_layer.forward(orange, orange_num)
all_price = add_apple_orange_layer.forward(apple_price, orange_price)
price = mul_tax_layer.forward(all_price, tax)

print(price)

dprice = 1
dall_price, dtax = mul_tax_layer.backward(dprice)
dapple_price, dorange_price = add_apple_orange_layer.backward(dall_price)
dorange, dorange_num = mul_orange_layer.backward(dorange_price)
dapple, dapple_num = mul_apple_layer.backward(dapple_price)

print(price)
print(dapple_num, dapple, dorange, dorange_num, dtax)

715.0000000000001
715.0000000000001
110.00000000000001 2.2 3.3000000000000003 165.0 650


In [15]:
# 5.5 活性化関数レイヤの実装
##5.5.1 ReLUレイヤ
import numpy as np


class Relu:
    def __init__(self):
        self.mask = None

    def forward(self, x):
        self.mask = x <= 0
        out = x.copy()
        out[self.mask] = 0

        return out

    def backward(self, dout):
        dout[self.mask] = 0
        dx = dout

        return dx


x = np.array([[1.0, -0.5], [-2.0, 3.0]])
print(x)

mask = x <= 0
print(mask)

[[ 1.  -0.5]
 [-2.   3. ]]
[[False  True]
 [ True False]]


In [16]:
##5.5.2 Sigmoidレイヤ
class Sigmoid:
    def __init__(self):
        self.out = None

    def forward(self, x):
        out = 1 / (1 + np.exp(-x))
        self.out = out

        return out

    def backward(self, dout):
        dx = dout * (1.0 - self.out) * self.out

        return dx

In [17]:
# 5.6 Affine / Softmaxレイヤ
# 5.6.1 Affineレイヤ

X = np.random.rand(2)
W = np.random.rand(2, 3)
B = np.random.rand(3)

X.shape
W.shape
B.shape

Y = np.dot(X, W) + B

X_dot_W = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([1, 2, 3])

print(X_dot_W)

print(X_dot_W + B)

dY = np.array([[1, 2, 3], [4, 5, 6]])
print(dY)

dB = np.sum(dY, axis=0)
print(dB)

[[1 2 3]
 [4 5 6]]
[[2 4 6]
 [5 7 9]]
[[1 2 3]
 [4 5 6]]
[5 7 9]


In [18]:
class Affine:
    def __init__(self, W, b):
        self.W = W
        self.b = b
        self.x = None
        self.dW = None
        self.db = None

    def forward(self, x):
        self.x = x
        out = np.dot(x, self.W) + self.b
        return out

    def backward(self, dout):
        # パズルタイム開始

        # dx（入力への勾配）を作るには、Wをひっくり返して(T)掛ける
        dx = np.dot(dout, self.W.T)

        # dW（重みへの勾配）を作るには、xをひっくり返して(T)掛ける
        self.dW = np.dot(self.x.T, dout)

        # db（バイアスへの勾配）は、縦方向に合計する（ここは丸暗記でいい）
        self.db = np.sum(dout, axis=0)

        return dx

In [ ]:
class softmaxWithLoss:
    def __init__(self):
        self.loss = None
        self.y = None
        self.t = None

    def forward(self, x, t):
        self.t = t
        self.y = softmax(x)
        self.loss = cross_entropy_error(self.y, self.t)

        return self.loss

    def backward(self, dout=1):
        batch_size = self.t.shape[0]
        dx = (self.y - self.t) / batch_size

        return dx

In [ ]:
import sys, os

sys.path.append(os.path.join(os.pardir, "deep-learning-from-scratch"))
import numpy as np
from common.layers import *
from common.gradient import numerical_gradient
from collections import OrderedDict


class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size, weight_init_std=0.01):
        # 重みの初期化
        self.params = {}
        self.params["W1"] = weight_init_std * np.random.randn(input_size, hidden_size)
        self.params["b1"] = np.zeros(hidden_size)
        self.params["W2"] = weight_init_std * np.random.randn(hidden_size, output_size)
        self.params["b2"] = np.zeros(output_size)

        # レイヤの生成
        self.layers = OrderedDict()
        self.layers["Affine"] = Affine(self.params["W1"], self.params["b1"])
        self.layers["Relu1"] = Relu()
        self.layers["Affine2"] = Affine(self.params["W2"], self.params["b2"])

        self.lastLayer = softmaxWithLoss()