In [ ]:
import numpy as np


def naive_convolve(image, filt):
    # 画像のサイズ（H:高さ, W:幅）
    hi, wi = image.shape
    # フィルターのサイズ
    hf, wf = filt.shape

    # 1. 出力サイズの計算 (Stride=1, Padding=0 の場合)
    # 5x5 の画像に 3x3 のフィルターをかけると、出力は (5-3+1) = 3x3 になる
    ho = hi - hf + 1
    wo = wi - wf + 1

    # 出力用の空の行列を用意
    output = np.zeros((ho, wo))

    # 2. スキャン開始（2重ループでフィルターを1マスずつ動かす）
    for i in range(ho):
        for j in range(wo):
            # 今、懐中電灯が照らしている範囲（局所領域）を切り出す
            region = image[i : i + hf, j : j + wf]

            # 3. 積和演算（フィルターと重なった部分を掛けて全部足す）
            output[i, j] = np.sum(region * filt)

    return output


# --- テスト用のデータ ---
# 5x5の適当な画像
image = np.array(
    [
        [1, 2, 3, 0, 1],
        [0, 1, 2, 3, 0],
        [3, 0, 1, 2, 3],
        [2, 3, 0, 1, 2],
        [1, 2, 3, 0, 1],
    ]
)

# 3x3のフィルター（例：縦の線を強調するようなフィルター）
filt = np.array([[1, 0, -1], [1, 0, -1], [1, 0, -1]])

# 実行
feature_map = naive_convolve(image, filt)

print("--- Original Image (5x5) ---")
print(image)
print("\n--- Filter (3x3) ---")
print(filt)
print("\n--- Output Feature Map (3x3) ---")
print(feature_map)

--- Original Image (5x5) ---
[[1 2 3 0 1]
 [0 1 2 3 0]
 [3 0 1 2 3]
 [2 3 0 1 2]
 [1 2 3 0 1]]

--- Filter (3x3) ---
[[ 1  0 -1]
 [ 1  0 -1]
 [ 1  0 -1]]

--- Output Feature Map (3x3) ---
[[-2. -2.  2.]
 [ 2. -2. -2.]
 [ 2.  2. -2.]]


In [ ]:
import sys, os

sys.path.append(os.path.join(os.pardir, "deep-learning-from-scratch"))